#!/usr/bin/env python3
"""Build the GitHub Pages entry point (index.html at the repo root) from app/index.html.

The app file is written for claude.ai artifacts, which wrap it in a doctype/head skeleton.
GitHub Pages serves files as-is, so this adds that skeleton and points relative URLs
(questions/, img/) at app/. Re-run after changing app/index.html, then commit both files.
"""
import os

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")

with open(os.path.join(ROOT, "app", "index.html"), encoding="utf-8") as fh:
    body = fh.read()

page = (
    "<!doctype html>\n<html lang=\"en\">\n<head>\n"
    "<meta charset=\"utf-8\">\n"
    "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, viewport-fit=cover\">\n"
    "<base href=\"app/\">\n"
    "<!-- Generated by tools/build_pages.py from app/index.html. Do not edit by hand. -->\n"
    "</head>\n<body>\n" + body + "\n</body>\n</html>\n"
)

with open(os.path.join(ROOT, "index.html"), "w", encoding="utf-8") as fh:
    fh.write(page)
print("wrote index.html")
